package ru.srqa.pft.addressbook;// Generated by Selenium IDE
import org.junit.Test;


public class GroupDeletionTests extends TestBase{
  
  @Test
  public void deleteUserGroup() {
    gotoGroupPage();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
    closeWebPage();
  }

}
