package ru.srqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;


public class GroupDeletionTests extends TestBase{
  
  @Test
  public void deleteUserGroup() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGroupsHelper().selectGroup();
    app.getGroupsHelper().deleteSelectedGroups();
    app.getGroupsHelper().returnToGroupPage();
    app.getNavigationHelper().closeWebPage();
  }

}
